development:
  dialect: postgres
  database: schutzstreifen
  user: schutzstreifen
  password: schutzstreifen
  host: 127.0.0.1
  pool: 5

test:
  url: {{envOr "TEST_DATABASE_URL" "postgres://schutzstreifen:schutzstreifen@127.0.0.1:5432/schutzstreifen_test?sslmode=disable"}}

production:
  url: {{envOr "DATABASE_URL" "postgres://schutzstreifen:schutzstreifen@127.0.0.1:5432/schutzstreifen_production?sslmode=disable"}}
