version: "3"

services:

  dev:
    build: ./docker/build/gobuffalo
    ports:
      - "22080:3000"
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/tardog/schutzstreifen:delegated
      - ./docker/volumes/postgresql:/var/lib/postgresql/data:delegated
    entrypoint: buffalo dev
    working_dir: /go/src/github.com/tardog/schutzstreifen
    environment:
      - ADDR=0.0.0.0

  db:
    build: ./docker/build/db
    restart: always
    ports:
      - "22543:5432"
    environment:
      POSTGRES_USER: schutzstreifen
      POSTGRES_PASSWORD: schutzstreifen
