version: "3"

services:
  build:
    build: ./docker/images/build
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/tardog/schutzstreifen
      - ./docker/volumes/db/:/var/lib/postgresql/data
    working_dir: /go/src/github.com/tardog/schutzstreifen

  db:
    build: ./docker/images/db
    environment:
      POSTGRES_USER: schutzstreifen
      POSTGRES_PASSWORD: schutzstreifen
