version: "3.1"

services:

  dev:
    image: gobuffalo/buffalo:v0.13.12
    ports:
      - "22080:3000"
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/tardog/schutzstreifen
    entrypoint: buffalo dev
    working_dir: /go/src/github.com/tardog/schutzstreifen
    environment:
      - ADDR=0.0.0.0

  db:
    image: postgres:11-alpine
    restart: always
    ports:
      - "22543:5432"
    environment:
      POSTGRES_USER: schutzstreifen
      POSTGRES_PASSWORD: schutzstreifen
