version: "3"

services:

  app:
    build: ./docker/images/app
    ports:
      - "22080:3000"
    depends_on:
      - db
    volumes:
      - .:/schutzstreifen
      - gocache:/go
      - ./docker/volumes/db/:/var/lib/postgresql/data
    environment:
      - ADDR=0.0.0.0
    working_dir: /schutzstreifen

  db:
    build: ./docker/images/db
    restart: always
    ports:
      - "22543:5432"
    environment:
      POSTGRES_USER: schutzstreifen
      POSTGRES_PASSWORD: schutzstreifen
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./docker/volumes/db:/var/lib/postgresql/data

  build:
    build: ./docker/images/build
    depends_on:
      - db
    volumes:
      - .:/schutzstreifen
      - gocache:/go
    working_dir: /schutzstreifen
    entrypoint: buffalo

volumes:
  gocache:
