version: "3"

services:

  app:
    build: ./docker/images/app
    ports:
      - "22080:3000"
    depends_on:
      - db
    volumes:
      - .:/go/src/github.com/tardog/schutzstreifen
      - ./docker/volumes/db/:/var/lib/postgresql/data
    environment:
      - ADDR=0.0.0.0

  db:
    build: ./docker/images/db
    restart: always
    ports:
      - "22543:5432"
    environment:
      POSTGRES_USER: schutzstreifen
      POSTGRES_PASSWORD: schutzstreifen
