version: "3.1"

services:

  web:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    links:
      - db:postgres

  db:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_USER: schutzstreifen
      POSTGRES_PASSWORD: schutzstreifen
