CREATE EXTENSION postgis;

CREATE TABLE users (
    id UUID PRIMARY KEY,
    name VARCHAR(100) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hazard_types (
    id UUID PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE hazards (
    id UUID PRIMARY KEY,
    label VARCHAR(255) NOT NULL,
    description VARCHAR(255) NOT NULL,
    lat numeric NOT NULL,
    lon numeric NOT NULL,
    visible BOOLEAN DEFAULT true,
    user_id UUID NOT NULL REFERENCES users(id),
    hazard_type_id UUID NOT NULL REFERENCES hazard_types(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
