package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/tardog/schutzstreifen/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (HazardType)
// DB Table: Plural (hazard_types)
// Resource: Plural (HazardTypes)
// Path: Plural (/hazard_types)
// View Template Folder: Plural (/templates/hazard_types/)

// HazardTypesResource is the resource for the HazardType model
type HazardTypesResource struct {
	buffalo.Resource
}

// List gets all HazardTypes. This function is mapped to the path
// GET /hazard_types
func (v HazardTypesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	hazardTypes := &models.HazardTypes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all HazardTypes from the DB
	if err := q.All(hazardTypes); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, hazardTypes))
}

// Show gets the data for one HazardType. This function is mapped to
// the path GET /hazard_types/{hazard_type_id}
func (v HazardTypesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty HazardType
	hazardType := &models.HazardType{}

	// To find the HazardType the parameter hazard_type_id is used.
	if err := tx.Find(hazardType, c.Param("hazard_type_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, hazardType))
}

// New renders the form for creating a new HazardType.
// This function is mapped to the path GET /hazard_types/new
func (v HazardTypesResource) New(c buffalo.Context) error {
	return c.Render(200, r.Auto(c, &models.HazardType{}))
}

// Create adds a HazardType to the DB. This function is mapped to the
// path POST /hazard_types
func (v HazardTypesResource) Create(c buffalo.Context) error {
	// Allocate an empty HazardType
	hazardType := &models.HazardType{}

	// Bind hazardType to the html form elements
	if err := c.Bind(hazardType); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(hazardType)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, hazardType))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "HazardType was created successfully")

	// and redirect to the hazard_types index page
	return c.Render(201, r.Auto(c, hazardType))
}

// Edit renders a edit form for a HazardType. This function is
// mapped to the path GET /hazard_types/{hazard_type_id}/edit
func (v HazardTypesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty HazardType
	hazardType := &models.HazardType{}

	if err := tx.Find(hazardType, c.Param("hazard_type_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, hazardType))
}

// Update changes a HazardType in the DB. This function is mapped to
// the path PUT /hazard_types/{hazard_type_id}
func (v HazardTypesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty HazardType
	hazardType := &models.HazardType{}

	if err := tx.Find(hazardType, c.Param("hazard_type_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind HazardType to the html form elements
	if err := c.Bind(hazardType); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(hazardType)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, hazardType))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "HazardType was updated successfully")

	// and redirect to the hazard_types index page
	return c.Render(200, r.Auto(c, hazardType))
}

// Destroy deletes a HazardType from the DB. This function is mapped
// to the path DELETE /hazard_types/{hazard_type_id}
func (v HazardTypesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty HazardType
	hazardType := &models.HazardType{}

	// To find the HazardType the parameter hazard_type_id is used.
	if err := tx.Find(hazardType, c.Param("hazard_type_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(hazardType); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "HazardType was destroyed successfully")

	// Redirect to the hazard_types index page
	return c.Render(200, r.Auto(c, hazardType))
}
