package actions

import (
	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop"
	"github.com/pkg/errors"
	"github.com/tardog/schutzstreifen/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Hazard)
// DB Table: Plural (hazards)
// Resource: Plural (Hazards)
// Path: Plural (/hazards)
// View Template Folder: Plural (/templates/hazards/)

// HazardsResource is the resource for the Hazard model
type HazardsResource struct {
	buffalo.Resource
}

// List gets all Hazards. This function is mapped to the path
// GET /hazards
func (v HazardsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	hazards := &models.Hazards{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Hazards from the DB
	if err := q.All(hazards); err != nil {
		return errors.WithStack(err)
	}

	// Add the paginator to the context so it can be used in the template.
	c.Set("pagination", q.Paginator)

	return c.Render(200, r.Auto(c, hazards))
}

// Show gets the data for one Hazard. This function is mapped to
// the path GET /hazards/{hazard_id}
func (v HazardsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Hazard
	hazard := &models.Hazard{}

	// To find the Hazard the parameter hazard_id is used.
	if err := tx.Find(hazard, c.Param("hazard_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, hazard))
}

// New renders the form for creating a new Hazard.
// This function is mapped to the path GET /hazards/new
func (v HazardsResource) New(c buffalo.Context) error {
	hazardTypes := []models.HazardType{}

	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	err := tx.All(&hazardTypes)
	if err != nil {
		return c.Error(500, err)
	}

	selectOptions := make(map[string]interface{})

	for _, hazardType := range hazardTypes {
		selectOptions[hazardType.Label] = hazardType.ID
	}

	c.Set("HazardTypes", selectOptions)

	return c.Render(200, r.Auto(c, &models.Hazard{}))
}

// Create adds a Hazard to the DB. This function is mapped to the
// path POST /hazards
func (v HazardsResource) Create(c buffalo.Context) error {
	// Allocate an empty Hazard
	hazard := &models.Hazard{}

	// Bind hazard to the html form elements
	if err := c.Bind(hazard); err != nil {
		return errors.WithStack(err)
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(hazard)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the new.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, hazard))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Hazard was created successfully")

	// and redirect to the hazards index page
	return c.Render(201, r.Auto(c, hazard))
}

// Edit renders a edit form for a Hazard. This function is
// mapped to the path GET /hazards/{hazard_id}/edit
func (v HazardsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Hazard
	hazard := &models.Hazard{}

	if err := tx.Find(hazard, c.Param("hazard_id")); err != nil {
		return c.Error(404, err)
	}

	return c.Render(200, r.Auto(c, hazard))
}

// Update changes a Hazard in the DB. This function is mapped to
// the path PUT /hazards/{hazard_id}
func (v HazardsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Hazard
	hazard := &models.Hazard{}

	if err := tx.Find(hazard, c.Param("hazard_id")); err != nil {
		return c.Error(404, err)
	}

	// Bind Hazard to the html form elements
	if err := c.Bind(hazard); err != nil {
		return errors.WithStack(err)
	}

	verrs, err := tx.ValidateAndUpdate(hazard)
	if err != nil {
		return errors.WithStack(err)
	}

	if verrs.HasAny() {
		// Make the errors available inside the html template
		c.Set("errors", verrs)

		// Render again the edit.html template that the user can
		// correct the input.
		return c.Render(422, r.Auto(c, hazard))
	}

	// If there are no errors set a success message
	c.Flash().Add("success", "Hazard was updated successfully")

	// and redirect to the hazards index page
	return c.Render(200, r.Auto(c, hazard))
}

// Destroy deletes a Hazard from the DB. This function is mapped
// to the path DELETE /hazards/{hazard_id}
func (v HazardsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return errors.WithStack(errors.New("no transaction found"))
	}

	// Allocate an empty Hazard
	hazard := &models.Hazard{}

	// To find the Hazard the parameter hazard_id is used.
	if err := tx.Find(hazard, c.Param("hazard_id")); err != nil {
		return c.Error(404, err)
	}

	if err := tx.Destroy(hazard); err != nil {
		return errors.WithStack(err)
	}

	// If there are no errors set a flash message
	c.Flash().Add("success", "Hazard was destroyed successfully")

	// Redirect to the hazards index page
	return c.Render(200, r.Auto(c, hazard))
}
